package view;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import object.Account;
import object.Bill;
import user.AccountFunctionImp;
import user.BillFunctionImp;

/**
 * Servlet implementation class dashBoard
 */
@WebServlet("/DashBoard")
public class DashBoard extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final String CONTENT_TYPE = "text/html; charset= utf-8";
    /**
     * @see HttpServlet#HttpServlet()
     */
    public DashBoard() {
        super();
		
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.setContentType(CONTENT_TYPE);
		BillFunctionImp oper1 = new BillFunctionImp(null);
		AccountFunctionImp oper2 = new AccountFunctionImp(null);
		String id = request.getParameter("id");
		ArrayList<Integer> salesProduct = oper1.getSaleQuantityByProduct(); // biểu đồ pie
		ArrayList<Integer> revenueByDate = oper1.getRevenueByDate(); // line chart
		ArrayList<Integer> salesByDate = oper1.getSalesByDate(); // trục x line chart
		ArrayList<String> date_stones = oper1.getDateList();
		ArrayList<Bill> cur_bill = oper1.getBill();
		
		PrintWriter out = response.getWriter();
		out.append("<!DOCTYPE html>");
		out.append("<html lang=\"en\">");
		out.append("");
		out.append("<head>");
		out.append("  <meta charset=\"utf-8\">");
		out.append("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">");
		out.append("");
		out.append("  <title>Quản lý tài khoản</title>");
		out.append("  <meta content=\"\" name=\"description\">");
		out.append("  <meta content=\"\" name=\"keywords\">");
		out.append("");
		out.append("  <!-- Favicons -->");
		out.append("  <link href=\"img/logo.jpg\" rel=\"icon\">");
		out.append("  <link href=\"img/logo.png\" rel=\"apple-touch-icon\">");
		out.append("");
		out.append("  <!-- Google Fonts -->");
		out.append("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">");
		out.append("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- Vendor CSS Files -->");
		out.append("  <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/all.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/bootstrap-icons.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/boxicons.min.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/quill.snow.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/quill.bubble.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/remixicon.css\" rel=\"stylesheet\">");
		out.append("  <link href=\"css/styleDb.css\" rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- Template Main CSS File -->");
		out.append("  <link href=\"css/styleAdmin.css\" rel=\"stylesheet\">");
		out.append("");
		out.append("  <!-- =======================================================");
		out.append("  * Template Name: NiceAdmin");
		out.append("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/");
		out.append("  * Updated: Apr 20 2024 with Bootstrap v5.3.3");
		out.append("  * Author: BootstrapMade.com");
		out.append("  * License: https://bootstrapmade.com/license/");
		out.append("  ======================================================== -->");
		out.append("</head>");
		out.append("");
		out.append("<body>");
		out.append("");
		out.append("  <!-- ======= Header ======= -->");
		out.append("  <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">");
		out.append("");
		out.append("    <div class=\"d-flex align-items-center justify-content-between\">");
		out.append("      <a href=\"dashBoard?id="+id+"\" class=\"logo d-flex align-items-center\">");
		out.append("        <img src=\"img/logo.png\" alt=\"\">");
		out.append("        <span class=\"d-none d-lg-block\">Tasty</span>");
		out.append("      </a>");
		out.append("      <i class=\"bi bi-list toggle-sidebar-btn\"></i>");
		out.append("    </div><!-- End Logo -->");
		out.append("");
		out.append("    <div class=\"search-bar\">");
		out.append("      <form class=\"search-form d-flex align-items-center\" method=\"POST\" action=\"#\">");
		out.append("        <input type=\"text\" name=\"query\" placeholder=\"Search\" title=\"Enter search keyword\">");
		out.append("        <button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\"></i></button>");
		out.append("      </form>");
		out.append("    </div><!-- End Search Bar -->");
		out.append("");
		out.append("    <nav class=\"header-nav ms-auto\">");
		out.append("      <ul class=\"d-flex align-items-center\">");
		out.append("");
		out.append("        <li class=\"nav-item d-block d-lg-none\">");
		out.append("          <a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">");
		out.append("            <i class=\"bi bi-search\"></i>");
		out.append("          </a>");
		out.append("        </li><!-- End Search Icon-->");
		out.append("");
		out.append("        <li class=\"nav-item dropdown\">");
		out.append("");
		out.append("          <a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("            <i class=\"bi bi-bell\"></i>");
		out.append("            <!-- <span class=\"badge bg-primary badge-number\">4</span> -->");
		out.append("          </a><!-- End Notification Icon -->");
		out.append("");
		out.append("          <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications\">");
		out.append("            <li class=\"dropdown-header\">");
		out.append("              Bạn không có thông báo nào");
		out.append("              <!-- <a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a> -->");
		out.append("            </li>");
		out.append("");
		out.append("          </ul><!-- End Notification Dropdown Items -->");
		out.append("");
		out.append("        </li><!-- End Notification Nav -->");
		out.append("");
		out.append("        <li class=\"nav-item dropdown\">");
		out.append("");
		out.append("          <a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("            <i class=\"bi bi-chat-left-text\"></i>");
		out.append("            <!-- <span class=\"badge bg-success badge-number\">3</span> -->");
		out.append("          </a><!-- End Messages Icon -->");
		out.append("");
		out.append("          <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">");
		out.append("            <li class=\"dropdown-header\">");
		out.append("              Bạn không có tin nhắn nào");
		out.append("            </li>");
		out.append("");
		out.append("          </ul><!-- End Messages Dropdown Items -->");
		out.append("");
		out.append("        </li><!-- End Messages Nav -->");
		out.append("");
		out.append("        <li class=\"nav-item dropdown pe-3\">");
		out.append("");
		out.append("          <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("<i class=\"fa-solid fa-user rounded-circle\"></i>");
		out.append("            <span class=\"d-none d-md-block dropdown-toggle ps-2\">Admin</span>");
		out.append("          </a><!-- End Profile Iamge Icon -->");
		out.append("");
		out.append("          <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">");
		out.append("            <li class=\"dropdown-header\">");
		out.append("              <h6>Admin</h6>");
		out.append("              <span>IT</span>");
		out.append("            </li>");
		out.append("            <li>");
		out.append("              <hr class=\"dropdown-divider\">");
		out.append("            </li>");
		out.append("");
		out.append("");
		out.append("            <li>");
		out.append("              <a class=\"dropdown-item d-flex align-items-center\" href=\"login\">");
		out.append("                <i class=\"bi bi-box-arrow-right\"></i>");
		out.append("                <span>Thoát</span>");
		out.append("              </a>");
		out.append("            </li>");
		out.append("");
		out.append("          </ul><!-- End Profile Dropdown Items -->");
		out.append("        </li><!-- End Profile Nav -->");
		out.append("");
		out.append("      </ul>");
		out.append("    </nav><!-- End Icons Navigation -->");
		out.append("");
		out.append("  </header><!-- End Header -->");
		out.append("");
		out.append("  <!-- ======= Sidebar ======= -->");
		out.append("  <aside id=\"sidebar\" class=\"sidebar\">");
		out.append("");
		out.append("    <ul class=\"sidebar-nav\" id=\"sidebar-nav\">");
		out.append("      <li class=\"nav-item\">");
		out.append("        <a class=\"nav-link collapsed\" href=\"DashBoard?id="+id+"\">");
		out.append("          <i class=\"bi bi-grid\"></i><span>Dashboard</span>");
		out.append("        </a>");
		out.append("        <a class=\"nav-link collapsed\" href=\"AccountManagermentSection?id="+id+"\">");
		out.append("          <i class=\"bi bi-layout-text-window-reverse\"></i><span>Quản lý tài khoản </span>");
		out.append("        </a>");
		out.append("		<a class=\"nav-link collapsed\" href=\"ManageOrders?id="+id+"\">");
		out.append("			<i class=\"fa-solid fa-receipt\"></i>");
		out.append("			<span class=\"ms-3\">Hóa đơn</span>");
		out.append("		</a>");
		out.append("      </li><!-- End Tables Nav -->");
		out.append("	  ");
		out.append("    </ul>");
		out.append("");
		out.append("  </aside><!-- End Sidebar-->");
		out.append("");
		
		
		
		
		
		 out.append("<main id=\"main\" class=\"main\">");
		 out.append("");
		 out.append("    <div class=\"pagetitle\">");
		 out.append("      <h1>Dashboard</h1>");
		 out.append("      <nav>");
		 out.append("        <ol class=\"breadcrumb\">");
		 out.append("          <li class=\"breadcrumb-item\"><a href=\"dashBoard?id="+id+"\">Home</a></li>");
		 out.append("          <li class=\"breadcrumb-item active\">Dashboard</li>");
		 out.append("        </ol>");
		 out.append("      </nav>");
		 out.append("    </div><!-- End Page Title -->");
		 out.append("");
		 out.append("    <section class=\"section dashboard\">");
		 out.append("      <div class=\"row\">");
		 out.append("");
		 out.append("        <!-- Left side columns -->");
		 out.append("        <div class=\"col-lg-8\">");
		 out.append("          <div class=\"row\">");
		 out.append("");
		 out.append("            <!-- Sales Card -->");
		 out.append("            <div class=\"col-xxl-4 col-md-6\">");
		 out.append("              <div class=\"card info-card sales-card\">");
		 out.append("");
//		 out.append("                <div class=\"filter\">");
//		 out.append("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
//		 out.append("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
//		 out.append("                    <li class=\"dropdown-header text-start\">");
//		 out.append("                      <h6>Filter</h6>");
//		 out.append("                    </li>");
//		 out.append("");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
//		 out.append("                  </ul>");
//		 out.append("                </div>");
		 out.append("");
		 out.append("                <div class=\"card-body\">");
		 out.append("                  <h5 class=\"card-title\">Đơn hàng</h5>");
		 out.append("");
		 out.append("                  <div class=\"d-flex align-items-center\">");
		 out.append("                    <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">");
		 out.append("                      <i class=\"bi bi-cart\"></i>");
		 out.append("                    </div>");
		 out.append("                    <div class=\"ps-3\">");
		 out.append("                      <h6>"+oper1.getAmountSales()+"</h6>");
//		 out.append("                      <span class=\"text-success small pt-1 fw-bold\">12%</span> <span class=\"text-muted small pt-2 ps-1\">increase</span>");
		 out.append("");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("                </div>");
		 out.append("");
		 out.append("              </div>");
		 out.append("            </div><!-- End Sales Card -->");
		 out.append("");
		 out.append("            <!-- Revenue Card -->");
		 out.append("            <div class=\"col-xxl-4 col-md-6\">");
		 out.append("              <div class=\"card info-card revenue-card\">");
		 out.append("");
//		 out.append("                <div class=\"filter\">");
//		 out.append("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
//		 out.append("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
//		 out.append("                    <li class=\"dropdown-header text-start\">");
//		 out.append("                      <h6>Filter</h6>");
//		 out.append("                    </li>");
//		 out.append("");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
//		 out.append("                  </ul>");
//		 out.append("                </div>");
		 out.append("");
		 out.append("                <div class=\"card-body\">");
		 out.append("                  <h5 class=\"card-title\">Lợi nhuận <span></span></h5>");
		 out.append("");
		 out.append("                  <div class=\"d-flex align-items-center\">");
		 out.append("                    <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">");
		 out.append("                      <i class=\"bi bi-currency-dollar\"></i>");
		 out.append("                    </div>");
		 out.append("                    <div class=\"ps-3\">");
		 out.append("                      <h6>"+oper1.getTotal()+"M</h6>");
		 //out.append("                      <span class=\"text-success small pt-1 fw-bold\">8%</span> <span class=\"text-muted small pt-2 ps-1\">increase</span>");
		 out.append("");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("                </div>");
		 out.append("");
		 out.append("              </div>");
		 out.append("            </div><!-- End Revenue Card -->");
		 out.append("");
		 out.append("            <!-- Customers Card -->");
		 out.append("            <div class=\"col-xxl-4 col-xl-12\">");
		 out.append("");
		 out.append("              <div class=\"card info-card customers-card\">");
		 out.append("");
//		 out.append("                <div class=\"filter\">");
//		 out.append("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
//		 out.append("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
//		 out.append("                    <li class=\"dropdown-header text-start\">");
//		 out.append("                      <h6>Filter</h6>");
//		 out.append("                    </li>");
//		 out.append("");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
//		 out.append("                  </ul>");
//		 out.append("                </div>");
		 out.append("");
		 out.append("                <div class=\"card-body\">");
		 out.append("                  <h5 class=\"card-title\">Khách hàng </h5>");
		 out.append("");
		 out.append("                  <div class=\"d-flex align-items-center\">");
		 out.append("                    <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">");
		 out.append("                      <i class=\"bi bi-people\"></i>");
		 out.append("                    </div>");
		 out.append("                    <div class=\"ps-3\">");
		 out.append("                      <h6>"+oper2.getAmountOfAcc()+"</h6>");
//		 out.append("                      <span class=\"text-danger small pt-1 fw-bold\">12%</span> <span class=\"text-muted small pt-2 ps-1\">decrease</span>");
		 out.append("");
		 out.append("                    </div>");
		 out.append("                  </div>");
		 out.append("");
		 out.append("                </div>");
		 out.append("              </div>");
		 out.append("");
		 out.append("            </div><!-- End Customers Card -->");
		 out.append("");
		 out.append("            <!-- Reports -->");
		 out.append("            <div class=\"col-12\">");
		 out.append("              <div class=\"card\">");
		 out.append("");
		 out.append("                <div class=\"filter\">");
		 out.append("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		 out.append("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		 out.append("                    <li class=\"dropdown-header text-start\">");
		 out.append("                      <h6>Filter</h6>");
		 out.append("                    </li>");
		 out.append("");
		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
		 out.append("                  </ul>");
		 out.append("                </div>");
		 out.append("");
		 out.append("                <div class=\"card-body\">");
		 out.append("                  <h5 class=\"card-title\">Reports <span>/Today</span></h5>");
		 out.append("");
		 out.append("                  <!-- Line Chart -->");
		 out.append("                  <div id=\"reportsChart\"></div>");
		 out.append("");
		 out.append("                  <script>");
		 out.append("                    document.addEventListener(\"DOMContentLoaded\", () => {");
		 out.append("                      new ApexCharts(document.querySelector(\"#reportsChart\"), {");
		 out.append("                        series: [{");
		 out.append("                          name: 'Đơn hàng',");
		 out.append("                          data: "+salesByDate+",");
		 out.append("                        }, {");
		 out.append("                          name: 'Lợi nhuận',");
		 out.append("                          data: "+revenueByDate+"");
		 out.append("                        }],");
		 out.append("                        chart: {");
		 out.append("                          height: 350,");
		 out.append("                          type: 'area',");
		 out.append("                          toolbar: {");
		 out.append("                            show: false");
		 out.append("                          },");
		 out.append("                        },");
		 out.append("                        markers: {");
		 out.append("                          size: 4");
		 out.append("                        },");
		 out.append("                        colors: ['#4154f1', '#2eca6a', '#ff771d'],");
		 out.append("                        fill: {");
		 out.append("                          type: \"gradient\",");
		 out.append("                          gradient: {");
		 out.append("                            shadeIntensity: 1,");
		 out.append("                            opacityFrom: 0.3,");
		 out.append("                            opacityTo: 0.4,");
		 out.append("                            stops: [0, 200, 100000]");
		 out.append("                          }");
		 out.append("                        },");
		 out.append("                        dataLabels: {");
		 out.append("                          enabled: false");
		 out.append("                        },");
		 out.append("                        stroke: {");
		 out.append("                          curve: 'smooth',");
		 out.append("                          width: 2");
		 out.append("                        },");
		 out.append("                        xaxis: {");
		 out.append("                          type: 'datetime',");
		 out.append("                          categories: [");
		 for (int i = 0; i < date_stones.size(); i++) {
		     out.append("\"" + date_stones.get(i) + "\""); 
		     if (i < date_stones.size() - 1) {
		         out.append(", ");
		     }
		 }
		 out.append("                          ]");
		 out.append("                        },");
		 out.append("                        tooltip: {");
		 out.append("                          x: {");
		 out.append("                            format: 'dd/MM/yyyy'");
		 out.append("                          },");
		 out.append("                        }");
		 out.append("                      }).render();");
		 out.append("                    });");
		 out.append("                  </script>");
		 out.append("                  <!-- End Line Chart -->");
		 out.append("");
		 out.append("                </div>");
		 out.append("");
		 out.append("              </div>");
		 out.append("            </div><!-- End Reports -->");
		 out.append("");
		 out.append("            <!-- Recent Sales -->");
		 out.append("            <div class=\"col-12\">");
		 out.append("              <div class=\"card recent-sales overflow-auto\">");
		 out.append("");
//		 out.append("                <div class=\"filter\">");
//		 out.append("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
//		 out.append("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
//		 out.append("                    <li class=\"dropdown-header text-start\">");
//		 out.append("                      <h6>Filter</h6>");
//		 out.append("                    </li>");
//		 out.append("");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
//		 out.append("                  </ul>");
//		 out.append("                </div>");
		 out.append("");
		 out.append("                <div class=\"card-body\">");
		 out.append("                  <h5 class=\"card-title\">Đơn hàng gần đây<span></span></h5>");
		 out.append("");
		 out.append("                  <table class=\"table table-borderless \">");
		 out.append("                    <thead>");
		 out.append("                      <tr>");
		 out.append("                        <th scope=\"col\">Mã sản phẩm</th>");
		 out.append("                        <th scope=\"col\">Mã khách hàng</th>");
		 out.append("                        <th scope=\"col\">Số người</th>");
		 out.append("                        <th scope=\"col\">Message</th>");
//		 out.append("                        <th scope=\"col\"></th>");
		 out.append("                      </tr>");
		 out.append("                    </thead>");
		 out.append("                    <tbody>");
		 if(cur_bill != null) {
				for (Bill bill :cur_bill) {
					out.append("                  <tr >");
					out.append("                    <td>"+bill.getBill_id()+"</td>");
					out.append("                    <td>"+bill.getAcc_id()+"</td>");
					out.append("                    <td>"+bill.getParticipants()+"</td>");
					out.append("                    <td>"+bill.getMessage()+"</td>");
					out.append("                  </tr>");
				}
			}
			else {
				out.append("<tr><td colspan='8'>Không có dữ liệu.</td></tr>");
			}
		 out.append("                    </tbody>");
		 out.append("                  </table>");
		 out.append("");
		 out.append("                </div>");
		 out.append("");
		 out.append("              </div>");
		 out.append("            </div><!-- End Recent Sales -->");
		 out.append("");
//		 out.append("            <!-- Top Selling -->");
//		 out.append("            <div class=\"col-12\">");
//		 out.append("              <div class=\"card top-selling overflow-auto\">");
//		 out.append("");
//		 out.append("                <div class=\"filter\">");
//		 out.append("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
//		 out.append("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
//		 out.append("                    <li class=\"dropdown-header text-start\">");
//		 out.append("                      <h6>Filter</h6>");
//		 out.append("                    </li>");
//		 out.append("");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
//		 out.append("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
//		 out.append("                  </ul>");
//		 out.append("                </div>");
//		 out.append("");
//		 out.append("                <div class=\"card-body pb-0\">");
//		 out.append("                  <h5 class=\"card-title\">Top Selling <span>| Today</span></h5>");
//		 out.append("");
//		 out.append("                  <table class=\"table table-borderless\">");
//		 out.append("                    <thead>");
//		 out.append("                      <tr>");
//		 out.append("                        <th scope=\"col\">Preview</th>");
//		 out.append("                        <th scope=\"col\">Product</th>");
//		 out.append("                        <th scope=\"col\">Price</th>");
//		 out.append("                        <th scope=\"col\">Sold</th>");
//		 out.append("                        <th scope=\"col\">Revenue</th>");
//		 out.append("                      </tr>");
//		 out.append("                    </thead>");
//		 out.append("                    <tbody>");
//		 out.append("                      <tr>");
//		 out.append("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-1.jpg\" alt=\"\"></a></th>");
//		 out.append("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Ut inventore ipsa voluptas nulla</a></td>");
//		 out.append("                        <td>$64</td>");
//		 out.append("                        <td class=\"fw-bold\">124</td>");
//		 out.append("                        <td>$5,828</td>");
//		 out.append("                      </tr>");
//		 out.append("                      <tr>");
//		 out.append("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-2.jpg\" alt=\"\"></a></th>");
//		 out.append("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Exercitationem similique doloremque</a></td>");
//		 out.append("                        <td>$46</td>");
//		 out.append("                        <td class=\"fw-bold\">98</td>");
//		 out.append("                        <td>$4,508</td>");
//		 out.append("                      </tr>");
//		 out.append("                      <tr>");
//		 out.append("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-3.jpg\" alt=\"\"></a></th>");
//		 out.append("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Doloribus nisi exercitationem</a></td>");
//		 out.append("                        <td>$59</td>");
//		 out.append("                        <td class=\"fw-bold\">74</td>");
//		 out.append("                        <td>$4,366</td>");
//		 out.append("                      </tr>");
//		 out.append("                      <tr>");
//		 out.append("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-4.jpg\" alt=\"\"></a></th>");
//		 out.append("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Officiis quaerat sint rerum error</a></td>");
//		 out.append("                        <td>$32</td>");
//		 out.append("                        <td class=\"fw-bold\">63</td>");
//		 out.append("                        <td>$2,016</td>");
//		 out.append("                      </tr>");
//		 out.append("                      <tr>");
//		 out.append("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-5.jpg\" alt=\"\"></a></th>");
//		 out.append("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Sit unde debitis delectus repellendus</a></td>");
//		 out.append("                        <td>$79</td>");
//		 out.append("                        <td class=\"fw-bold\">41</td>");
//		 out.append("                        <td>$3,239</td>");
//		 out.append("                      </tr>");
//		 out.append("                    </tbody>");
//		 out.append("                  </table>");
//		 out.append("");
//		 out.append("                </div>");
//		 out.append("");
//		 out.append("              </div>");
//		 out.append("            </div><!-- End Top Selling -->");
		 out.append("");
		 out.append("          </div>");
		 out.append("        </div><!-- End Left side columns -->");
		 out.append("");
		 out.append("        <!-- Right side columns -->");
		 out.append("        <div class=\"col-lg-4\">");
		 out.append("");
		 out.append("          <!-- Website Traffic -->");
		 out.append("          <div class=\"card\">");
		 out.append("");
		 out.append("            <div class=\"card-body pb-0\">");
		 out.append("              <h5 class=\"card-title\">Thị phần dịch vụ <span></span></h5>");
		 out.append("");
		 out.append("              <div id=\"trafficChart\" style=\"min-height: 400px;\" class=\"echart\"></div>");
		 out.append("");
		 out.append("              <script>");
		 out.append("                document.addEventListener(\"DOMContentLoaded\", () => {");
		 out.append("                  echarts.init(document.querySelector(\"#trafficChart\")).setOption({");
		 out.append("                    tooltip: {");
		 out.append("                      trigger: 'item'");
		 out.append("                    },");
		 out.append("                    legend: {");
		 out.append("                      top: '5%',");
		 out.append("                      left: 'center'");
		 out.append("                    },");
		 out.append("                    series: [{");
		 out.append("                      name: 'Thông tin',");
		 out.append("                      type: 'pie',");
		 out.append("                      radius: ['0%', '70%'],");
		 out.append("                      avoidLabelOverlap: false,");
		 out.append("                      label: {");
		 out.append("                        show: false,");
		 out.append("                        position: 'center'");
		 out.append("                      },");
		 out.append("                      emphasis: {");
		 out.append("                        label: {");
		 out.append("                          show: false,");
		 out.append("                          fontSize: '18',");
		 out.append("                          fontWeight: 'normal'");
		 out.append("                        }");
		 out.append("                      },");
		 out.append("                      labelLine: {");
		 out.append("                        show: false");
		 out.append("                      },");
		 out.append("                      data: [{");
		 out.append("                          value: "+ salesProduct.get(0) +",");
		 out.append("                          name: 'Tiệc sinh nhật'");
		 out.append("                        },");
		 out.append("                        {");
		 out.append("                          value: "+ salesProduct.get(1) +",");
		 out.append("                          name: 'Tiệc tại gia'");
		 out.append("                        },");
		 out.append("                        {");
		 out.append("                          value: "+ salesProduct.get(2) +",");
		 out.append("                          name: 'Tiệc cưới'");
		 out.append("                        }");
		 out.append("                      ]");
		 out.append("                    }]");
		 out.append("                  });");
		 out.append("                });");
		 out.append("              </script>");
		 out.append("");
		 out.append("            </div>");
		 out.append("          </div><!-- End Website Traffic -->");
		 out.append("");
//		 out.append("          <!-- Recent Activity -->");
//		 out.append("          <div class=\"card\">");
//		 out.append("            <div class=\"filter\">");
//		 out.append("              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
//		 out.append("              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
//		 out.append("                <li class=\"dropdown-header text-start\">");
//		 out.append("                  <h6>Filter</h6>");
//		 out.append("                </li>");
//		 out.append("");
//		 out.append("                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>");
//		 out.append("                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>");
//		 out.append("                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>");
//		 out.append("              </ul>");
//		 out.append("            </div>");
//		 out.append("");
//		 out.append("            <div class=\"card-body\">");
//		 out.append("              <h5 class=\"card-title\">Recent Activity <span>| Today</span></h5>");
//		 out.append("");
//		 out.append("              <div class=\"activity\">");
//		 out.append("");
//		 out.append("                <div class=\"activity-item d-flex\">");
//		 out.append("                  <div class=\"activite-label\">32 min</div>");
//		 out.append("                  <i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>");
//		 out.append("                  <div class=\"activity-content\">");
//		 out.append("                    Quia quae rerum <a href=\"#\" class=\"fw-bold text-dark\">explicabo officiis</a> beatae");
//		 out.append("                  </div>");
//		 out.append("                </div><!-- End activity item-->");
//		 out.append("");
//		 out.append("                <div class=\"activity-item d-flex\">");
//		 out.append("                  <div class=\"activite-label\">56 min</div>");
//		 out.append("                  <i class='bi bi-circle-fill activity-badge text-danger align-self-start'></i>");
//		 out.append("                  <div class=\"activity-content\">");
//		 out.append("                    Voluptatem blanditiis blanditiis eveniet");
//		 out.append("                  </div>");
//		 out.append("                </div><!-- End activity item-->");
//		 out.append("");
//		 out.append("                <div class=\"activity-item d-flex\">");
//		 out.append("                  <div class=\"activite-label\">2 hrs</div>");
//		 out.append("                  <i class='bi bi-circle-fill activity-badge text-primary align-self-start'></i>");
//		 out.append("                  <div class=\"activity-content\">");
//		 out.append("                    Voluptates corrupti molestias voluptatem");
//		 out.append("                  </div>");
//		 out.append("                </div><!-- End activity item-->");
//		 out.append("");
//		 out.append("                <div class=\"activity-item d-flex\">");
//		 out.append("                  <div class=\"activite-label\">1 day</div>");
//		 out.append("                  <i class='bi bi-circle-fill activity-badge text-info align-self-start'></i>");
//		 out.append("                  <div class=\"activity-content\">");
//		 out.append("                    Tempore autem saepe <a href=\"#\" class=\"fw-bold text-dark\">occaecati voluptatem</a> tempore");
//		 out.append("                  </div>");
//		 out.append("                </div><!-- End activity item-->");
//		 out.append("");
//		 out.append("                <div class=\"activity-item d-flex\">");
//		 out.append("                  <div class=\"activite-label\">2 days</div>");
//		 out.append("                  <i class='bi bi-circle-fill activity-badge text-warning align-self-start'></i>");
//		 out.append("                  <div class=\"activity-content\">");
//		 out.append("                    Est sit eum reiciendis exercitationem");
//		 out.append("                  </div>");
//		 out.append("                </div><!-- End activity item-->");
//		 out.append("");
//		 out.append("                <div class=\"activity-item d-flex\">");
//		 out.append("                  <div class=\"activite-label\">4 weeks</div>");
//		 out.append("                  <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>");
//		 out.append("                  <div class=\"activity-content\">");
//		 out.append("                    Dicta dolorem harum nulla eius. Ut quidem quidem sit quas");
//		 out.append("                  </div>");
//		 out.append("                </div><!-- End activity item-->");
//		 out.append("");
//		 out.append("              </div>");
//		 out.append("");
//		 out.append("            </div>");
//		 out.append("          </div><!-- End Recent Activity -->");
		 out.append("");
		 out.append("        </div><!-- End Right side columns -->");
		 out.append("");
		 out.append("      </div>");
		 out.append("    </section>");
		 out.append("");
		 out.append("  </main><!-- End #main -->");
		out.append("");
		
		
		
		
		out.append("  <!-- ======= Footer ======= -->");
		out.append("  <footer id=\"footer\" class=\"footer\">");
		out.append("    <div class=\"copyright\">");
		out.append("      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved");
		out.append("    </div>");
		out.append("    <div class=\"credits\">");
		out.append("      <!-- All the links in the footer should remain intact. -->");
		out.append("      <!-- You can delete the links only if you purchased the pro version. -->");
		out.append("      <!-- Licensing information: https://bootstrapmade.com/license/ -->");
		out.append("      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->");
		out.append("      Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>");
		out.append("    </div>");
		out.append("  </footer><!-- End Footer -->");
		out.append("");
		out.append("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>");
		out.append("");
		out.append("  <!-- Vendor JS Files -->");
		out.append("  <script src=\"js/apexcharts.min.js\"></script>");
		out.append("  <script src=\"js/bootstrap.bundle.min.js\"></script>");
		out.append("  <script src=\"js/chart.umd.js\"></script>");
		out.append("  <script src=\"js/echarts.min.js\"></script>");
		out.append("  <script src=\"js/quill.js\"></script>");
		out.append("  <script src=\"js/simple-datatables.js\"></script>");
		out.append("  <script src=\"js/tinymce.min.js\"></script>");
		out.append("  <script src=\"js/validate.js\"></script>");
		out.append("");
		out.append("  <!-- Template Main JS File -->");
		out.append("  <script src=\"js/mainAdmin.js\"></script>");
		out.append("");
		out.append("</body>");
		out.append("");
		out.append("</html>");
		out.close();
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
	}

}
